### ISSUE TITLE
Буквица

### ISSUE THREAD

**Issue by AKryukov92** [AKryukov92/dev007oct17#13]
Эпик: #12 
Буквица - крупная, отличная от прочих, первая буква главы, раздела или целой книги.

Требования:
* Первая буква должна занимать 4 строки обычного текста.
* Текст сказки должен ее обтекать справа.
* Шрифт должен отличаться от остального текста.
* Цвет - красный.
* Допустимо использовать картинку.

**Comment by kotanek13** [comment]
Буквица картинкой добавлена
